name = "claude-nexus-proxy"
main = "./index.ts"
compatibility_date = "2025-05-30"
compatibility_flags = ["nodejs_compat"]

[vars]
# DEBUG = "true"
# REASONING_MODEL = "deepseek/deepseek-r1-0528:free"
# COMPLETION_MODEL = "deepseek/deepseek-r1-0528:free"
# REASONING_MAX_TOKENS = "4096"
# COMPLETION_MAX_TOKENS = "2048"
# PROXY_MODE = "passthrough"  # 'translation' or 'passthrough'
# CLAUDE_API_KEY = "sk-ant-..."  # For passthrough mode
# DOMAIN_CREDENTIAL_MAPPING = '{"claude-1.kaki.dev":"credentials/team1.json","claude-2.kaki.dev":"credentials/team2.json"}'
# TELEMETRY_ENDPOINT = "https://your-telemetry-server.com/api/events"
# SLACK_WEBHOOK_URL = "https://hooks.slack.com/services/T00000000/B00000000/XXXXXXXXXXXXXXXXXXXXXXXX"
# SLACK_CHANNEL = "#claude-proxy-logs"
# SLACK_USERNAME = "Claude Nexus Proxy"
# SLACK_ICON_EMOJI = ":robot_face:"
# SLACK_ENABLED = "true"
