# ServiceMonitor for Prometheus Operator
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: claude-nexus-proxy
  labels:
    app: claude-nexus-proxy
    prometheus: kube-prometheus
spec:
  selector:
    matchLabels:
      app: claude-nexus-proxy
  endpoints:
  - port: http
    interval: 30s
    path: /metrics
    scheme: http
---
# PrometheusRule for alerting
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: claude-nexus-proxy
  labels:
    app: claude-nexus-proxy
    prometheus: kube-prometheus
spec:
  groups:
  - name: claude-proxy.rules
    interval: 30s
    rules:
    # High error rate
    - alert: ClaudeProxyHighErrorRate
      expr: |
        (
          sum(rate(claude_proxy_requests_total{status=~"5.."}[5m])) by (job)
          /
          sum(rate(claude_proxy_requests_total[5m])) by (job)
        ) > 0.05
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "High error rate on Claude Proxy"
        description: "Error rate is {{ $value | humanizePercentage }} for {{ $labels.job }}"
    
    # Circuit breaker open
    - alert: ClaudeProxyCircuitBreakerOpen
      expr: claude_proxy_circuit_breaker_state{name="claude-api"} == 1
      for: 1m
      labels:
        severity: critical
      annotations:
        summary: "Claude API circuit breaker is OPEN"
        description: "Claude API is unavailable, circuit breaker has opened"
    
    # High memory usage
    - alert: ClaudeProxyHighMemoryUsage
      expr: |
        (
          claude_proxy_memory_usage_bytes / 1024 / 1024
        ) > 400
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "High memory usage on Claude Proxy"
        description: "Memory usage is {{ $value | humanize }}MB"
    
    # Database connection pool exhausted
    - alert: ClaudeProxyDBPoolExhausted
      expr: |
        claude_proxy_db_pool_available == 0
      for: 1m
      labels:
        severity: critical
      annotations:
        summary: "Database connection pool exhausted"
        description: "No available database connections"
    
    # High rate limit rejections
    - alert: ClaudeProxyHighRateLimitRejections
      expr: |
        sum(rate(claude_proxy_rate_limit_rejections_total[5m])) > 10
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "High rate of rate limit rejections"
        description: "{{ $value | humanize }} requests/sec being rate limited"
---
# Grafana Dashboard ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: claude-proxy-dashboard
  labels:
    app: claude-nexus-proxy
    grafana_dashboard: "1"
data:
  claude-proxy-dashboard.json: |
    {
      "dashboard": {
        "title": "Claude Nexus Proxy",
        "panels": [
          {
            "title": "Request Rate",
            "targets": [
              {
                "expr": "sum(rate(claude_proxy_requests_total[5m])) by (status)"
              }
            ]
          },
          {
            "title": "Token Usage",
            "targets": [
              {
                "expr": "sum(rate(claude_proxy_tokens_total[5m])) by (type)"
              }
            ]
          },
          {
            "title": "Circuit Breaker State",
            "targets": [
              {
                "expr": "claude_proxy_circuit_breaker_state"
              }
            ]
          },
          {
            "title": "Response Time P95",
            "targets": [
              {
                "expr": "histogram_quantile(0.95, rate(claude_proxy_request_duration_seconds_bucket[5m]))"
              }
            ]
          },
          {
            "title": "Memory Usage",
            "targets": [
              {
                "expr": "claude_proxy_memory_usage_bytes / 1024 / 1024"
              }
            ]
          },
          {
            "title": "Database Connections",
            "targets": [
              {
                "expr": "claude_proxy_db_pool_size - claude_proxy_db_pool_available"
              }
            ]
          }
        ]
      }
    }