# Docker Compose configuration for local development with locally built images
# 
# Usage from project root:
#   ./docker-up.sh -f docker-compose.local.yml up -d
# Or from docker directory:
#   docker compose -f docker-compose.local.yml --env-file ../.env up -d
#
# This file uses locally built images instead of registry images

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: agent-prompttrain-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: claude_proxy
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ../scripts/init-database.sql:/docker-entrypoint-initdb.d/01-init.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Proxy Service - Built locally
  proxy:
    build:
      context: ../
      dockerfile: docker/proxy/Dockerfile
    image: agent-prompttrain-proxy:local
    container_name: agent-prompttrain-proxy
    environment:
      # Server configuration
      PORT: 3000
      HOST: 0.0.0.0
      
      # Claude API configuration
      CREDENTIALS_DIR: /app/credentials
      
      # Database configuration
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/claude_proxy
      STORAGE_ENABLED: "true"
      
      # Telemetry
      TELEMETRY_ENDPOINT: ${TELEMETRY_ENDPOINT}
      
      # Slack notifications (optional)
      SLACK_WEBHOOK_URL: ${SLACK_WEBHOOK_URL}
      SLACK_CHANNEL: ${SLACK_CHANNEL}
      SLACK_USERNAME: ${SLACK_USERNAME:-Agent Prompt Train}
      SLACK_ICON_EMOJI: ${SLACK_ICON_EMOJI:-:robot_face:}
      SLACK_ENABLED: ${SLACK_ENABLED:-false}
      
      # Debug
      DEBUG: ${DEBUG:-false}
      
      # Client authentication
      ENABLE_CLIENT_AUTH: ${ENABLE_CLIENT_AUTH:-false}
    volumes:
      - ../credentials:/app/credentials
      - ../client-setup:/app/client-setup:ro
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Dashboard Service - Built locally
  dashboard:
    build:
      context: ../
      dockerfile: docker/dashboard/Dockerfile
    image: agent-prompttrain-dashboard:local
    environment:
      # Server configuration
      PORT: 3001
      HOST: 0.0.0.0
      
      # Dashboard authentication 
      DASHBOARD_API_KEY: ${DASHBOARD_API_KEY}
      
      # Proxy API URL for data access
      PROXY_API_URL: http://proxy:3000
      
      # Database configuration
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/claude_proxy
    ports:
      - "3001:3001"
    depends_on:
      proxy:
        condition: service_started
    restart: unless-stopped


  # Claude CLI Service - Run Claude CLI connected to the proxy
  claude-cli:
    build:
      context: ./claude-cli
      dockerfile: Dockerfile
    container_name: claude-cli
    environment:
      # Proxy configuration for Claude Code
      ANTHROPIC_BASE_URL: http://proxy:3000
    volumes:
      # Mount the entire project for Claude Code functionality
      - ../:/workspace
    depends_on:
      proxy:
        condition: service_started
    stdin_open: true
    tty: true
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  postgres_data:
  claude_data:

networks:
  default:
    name: agent-prompttrain-network