name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Check code formatting
        run: bun run format:check

      - name: Build shared package
        run: bun run build:shared

      - name: Run type checks
        run: bun run typecheck

      - name: Build proxy service
        run: bun run build:proxy

      - name: Build dashboard service
        run: bun run build:dashboard

      - name: Run tests
        run: bun test

      - name: Build Docker images
        run: |
          cd docker
          ./build-images.sh

      - name: Verify production builds
        run: |
          echo "Checking proxy production build..."
          if [ -d "services/proxy/dist" ]; then
            echo "✅ Proxy build successful"
          else
            echo "❌ Proxy build failed - dist directory not found"
            exit 1
          fi

          echo "Checking dashboard production build..."
          if [ -d "services/dashboard/dist" ]; then
            echo "✅ Dashboard build successful"
          else
            echo "❌ Dashboard build failed - dist directory not found"
            exit 1
          fi

  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Run linting
        run: bun run lint
        continue-on-error: true # Don't fail if lint script doesn't exist yet
