name: Docker Validation

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  validate-docker:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: network=host

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Build shared package
        run: bun run build:shared

      - name: Run Docker validation
        run: |
          chmod +x scripts/validate-docker.sh
          ./scripts/validate-docker.sh
        env:
          BUILD_PLATFORMS: linux/amd64
          BUILD_ACTION: load

      - name: Upload Docker logs on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: docker-validation-logs
          path: docker-compose-logs.txt
          retention-days: 7
          if-no-files-found: warn

      - name: Cleanup
        if: always()
        run: |
          docker compose -f docker/docker-compose.yml down --volumes --remove-orphans || true
