name: AI-Driven Generative Tests

on:
  workflow_dispatch:
    inputs:
      test_mode:
        description: 'Test mode (generate or replay)'
        required: false
        default: 'generate'
        type: choice
        options:
          - generate
          - replay
      replay_suite_id:
        description: 'Suite ID for replay mode'
        required: false
        type: string
  schedule:
    # Run nightly at 2 AM UTC
    - cron: '0 2 * * *'

jobs:
  run-ai-tests:
    runs-on: ubuntu-latest
    # Don't fail the workflow if tests fail (experimental)
    continue-on-error: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Create secrets directory
        run: mkdir -p secrets

      - name: Create API key secret files
        run: |
          echo "${{ secrets.ANTHROPIC_API_KEY }}" > secrets/anthropic_api_key.txt
          echo "${{ secrets.CLIENT_API_KEY || 'cnp_test_default_key' }}" > secrets/client_api_key.txt
          chmod 600 secrets/*.txt

      - name: Build test image
        run: |
          cd docker
          docker compose build claude-testing

      - name: Run AI-driven tests
        env:
          TEST_MODE: ${{ github.event.inputs.test_mode || 'generate' }}
          REPLAY_SUITE_ID: ${{ github.event.inputs.replay_suite_id }}
        run: |
          cd docker
          docker compose --profile testing up \
            --exit-code-from claude-testing \
            --abort-on-container-exit

      - name: Upload test artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: generative-test-artifacts-${{ github.run_id }}-${{ github.run_attempt }}
          path: tests/e2e-ai/artifacts/
          retention-days: 30

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-${{ github.run_id }}-${{ github.run_attempt }}
          path: tests/e2e-ai/artifacts/test-results.xml
          retention-days: 30

      - name: Parse test results
        if: always()
        run: |
          if [ -f "tests/e2e-ai/artifacts/test-results.xml" ]; then
            echo "📊 Test Results Summary:"
            # Basic parsing of JUnit XML results
            grep -E "(testsuites|testsuite|testcase)" tests/e2e-ai/artifacts/test-results.xml || true
          fi

      - name: Notify on failure
        if: failure() && github.event_name == 'schedule'
        uses: actions/github-script@v7
        with:
          script: |
            const runUrl = `${context.serverUrl}/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}`;
            await github.rest.issues.create({
              ...context.repo,
              title: `🤖 Nightly AI Tests Failed - ${new Date().toISOString().split('T')[0]}`,
              body: `The nightly AI-driven tests have discovered potential issues.\n\n[View test run](${runUrl})\n\nPlease review the test artifacts to investigate any legitimate bugs found by the AI.`,
              labels: ['ai-testing', 'automated']
            })
